[tools]
bat = { version = "latest", postinstall = "bat cache --build" }
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
go = "latest"
java = "temurin-25"
jq = "latest"
lazygit = "latest"
neovim = "latest"
node = "lts"
ripgrep = "latest"
usage = "latest"
yazi = { version = "latest", postinstall = "ya pkg install" }
zoxide = "latest"
