[tools]
bat = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
go = "latest"
java = "temurin-25"
jq = "latest"
lazygit = "latest"
neovim = "latest"
node = "lts"
ripgrep = "latest"
usage = "latest"
yazi = "latest"
zoxide = "latest"
